### ISSUE TITLE
Docker CLI Client Inheritance

### ISSUE THREAD

**Issue by ambsw-technology** [merll/docker-fabric#10]
Around line 85 of `dockermap.map.client`, a check is run looking for (among other things) a  `docker.Client`.  `DockerFabricClient` passes because it inherits (indirectly) from this class but the `DockerCliClient` does not (it only inherits from `DockerUtilityMixin`).

```
Traceback (most recent call last):
  File "/mnt/data/.virtualenvs/build_deploy/local/lib/python2.7/site-packages/fabric/main.py", line 756, in main
    *args, **kwargs
  File "/mnt/data/.virtualenvs/build_deploy/local/lib/python2.7/site-packages/fabric/tasks.py", line 426, in execute
    results['<local-only>'] = task.run(*args, **new_kwargs)
  File "/mnt/data/.virtualenvs/build_deploy/local/lib/python2.7/site-packages/fabric/tasks.py", line 173, in run
    return self.wrapped(*args, **kwargs)
  File "/mnt/data/apex-server/build_deploy/src/fabfile.py", line 898, in setup_service_graylog
    startup_required_containers(db_client)
  File "/mnt/data/apex-server/build_deploy/src/fabfile.py", line 1903, in startup_required_containers
    container_fabric_inst = container_fabric(docker_client=docker_client, container_maps=[])
  File "/mnt/data/.virtualenvs/build_deploy/local/lib/python2.7/site-packages/dockerfabric/api.py", line 48, in container_fabric
    return ContainerCliFabricClient(container_maps, docker_client, clients)
  File "/mnt/data/.virtualenvs/build_deploy/local/lib/python2.7/site-packages/dockerfabric/base.py", line 99, in __init__
    clients=current_clients)
  File "/mnt/data/.virtualenvs/build_deploy/local/lib/python2.7/site-packages/dockermap/map/client.py", line 85, in __init__
    raise ValueError("Unexpected type of 'docker_client' argument: {0}".format(type(docker_client)))
ValueError: Unexpected type of 'docker_client' argument: <class 'dockerfabric.cli.DockerCliClient'>
```

**Comment by ambsw-technology** [comment]
I didn't see anything objectionable in `DockerClientWrapper` so I switched the parent of `DockerCliClient` to `DockerClientWrapper` and it resolved this issue (although I haven't run a test suite or anything).

**Comment by merll** [comment]
Thanks for the report. The issue can probably most easily resolved by removing the subclass check from ``Docker-Map``, as it seems unnecessarily strict.

**Comment by ambsw-technology** [comment]
Adding `docker.Client` to the CLI dependency tree may be contributing to my other issue so I'll try this first (and revert the dependency on the CLI client).

**Comment by ambsw-technology** [comment]
Yes.  Progress.  I changed the Docker map check to:

```
            if isinstance(docker_client, ClientConfiguration):
                default_client = docker_client
            else:
                default_client = self.configuration_class.from_client(docker_client)
```

This filters out configs, but assumes anything else will behave correctly.

**Comment by ambsw-technology** [comment]
I also removed (un-added) `docker.Client` as a dependency on the CLI and the command is now:

`docker ps --no-trunc --format="{{.ID}}||{{.Image}}||{{.CreatedAt}}||{{.Status}}||{{.Names}}||{{.Command}}||{{.Ports}}" --all=true`

so the `-H` is gone.  There's a new issue that I'll hunt down but this (or something comparable) will close this issue.

**Comment by ambsw-technology** [comment]
Closing and moving fix to `docker-map`
